### ISSUE TITLE
failed to toggle bookmark

### ISSUE THREAD

**Issue by HoiPangCHEUNG** [thomassth/ttc-bus-eta#20]
### Issue
When an item is bookmarked, it can only be cleared on the main page, clicking the bookmark Item will do nothing

### How to reproduce
- randomly select a stop (e.g. https://thomassth.github.io/ttc-eta/stops/14684)
- bookmarked it by clicking the bookmark button
- try clicking the button again to un-bookmark it

## expected behaviour
- un-bookmarking a stop smoothly

## actual behaviour
- failed to un-bookmark a stop

**Comment by thomassth** [comment]
Closed with #23
