### ISSUE TITLE
button for bookmarking specific route instead of whole stops

### ISSUE THREAD

**Issue by HoiPangCHEUNG** [thomassth/ttc-bus-eta#67]
when bookmarking stops, some of the route info is useless to users, it is better for us to introduce bookmarkButton for individual route, or just showing the searched one in `stops` page

**Comment by thomassth** [comment]
this may lead to complicated / confusing UI.

Will continue on stop-based approach, and unifying all route ETA data.

Not considered until there's a good enough UI for said feature.

**Comment by thomassth** [comment]
Implemented with fd4bc1c13d457af5f3c91ba5536c0f5e39af13cd
